#include "./catch.hpp"
#include "./CTestDb.h"
#include "./Runner.h"
#include "./RoomBuilder.h"
#include "../../DRODLib/CurrentGame.h"
#include "../../DRODLib/CurrentGame.h"
#include "../../DRODLib/Character.h"
#include "../../DRODLib/CharacterCommand.h"